### ISSUE TITLE
Hej Steen

### ISSUE THREAD

**Issue by ciaran-dk** [monis4567/Analysis_MONIS5_to_6_v01#2]
@monis4567 - jeg laver en lille overspringshandling og har tilføjet confidence intervals. Men... hver gang jeg prøver at lave en pull request får jeg konflikter fordi du sidder stadig og retter i samme fil.

Det er vel bedst at vi retter i samme fil. Hvis jeg bare tilføjer en helt ny kopi af filen, så, kan du ikke følge med i hvad der er ændret. Sig til når du holder 10 minutters pause - så kan jeg tilføje confidence koden til den seneste version af filen

**Comment by monis4567** [comment]
Beklager. Jeg holder for idag. Jeg skal lave aftensmad nu. Det er lidt kringlet det her github, Men det er en god øvelse for mig. Giv den gas med konfidens intervaller jeg går i køkkenet . God weekend.
